camunda:
  bpm:
#    admin-user:
#      id: CamundaAdmin
#      password: CamundaAdmin
#      firstName: Camunda
#      lastName: Admin
#      email: CamundaAdmin@camunda.com
    authorization:
      enabled: true
#      enabled-for-custom-code: true
#    enableExceptionsAfterUnhandledBpmnError: true
    filter:
      create: All tasks
    generic-properties:
      properties:
         # History Cleanup
#        historyCleanupStrategy: removalTimeBased
#        historyRemovalTimeStrategy: end
#        historyTimeToLive: 30
#        batchOperationHistoryTimeToLive: 1
#        historyCleanupJobLogTimeToLive: 1
#        historyCleanupBatchWindowStartTime: "00:00"
#        historyCleanupBatchWindowEndTime: "10:00"
#        saturdayHistoryCleanupBatchWindowStartTime: "21:00"
#        saturdayHistoryCleanupBatchWindowEndTime: "02:00"
#        sundayHistoryCleanupBatchWindowStartTime: "21:00"
#        sundayHistoryCleanupBatchWindowEndTime: "02:00"
         # MDC Logging
#        loggingContextActivityId: activityName
         # Tasklist Query
#        queryMaxResultsLimit: 2000
         # Telemetry
        initializeTelemetry: false
        telemetryReporterActivate: false
    id-generator: strong # Values: strong, prefixed, or simple (simple is not recommended).
    job-execution:
      enabled: true

security:
  ldap:
    initialContextFactory: com.sun.jndi.ldap.LdapCtxFactory
    securityAuthentication: simple
    serverUrl: ldaps://MOLLY.AQUARIUM.tank:636
    managerDn: CN=CamundaAdmin,CN=Users,DC=AQUARIUM,DC=tank
    managerPassword: CamundaAdmin
    baseDn: DC=AQUARIUM,DC=tank
    userDnPattern:
    userSearchBase: CN=Users
    userSearchFilter: (objectclass=person)
    groupSearchBase:
    groupSearchFilter: (objectclass=group)
    userIdAttribute: cn
    userFirstnameAttribute: givenName
    userLastnameAttribute: sn
    userEmailAttribute: mail
    userPasswordAttribute: userpassword
    groupIdAttribute: cn
    groupNameAttribute: name
    groupTypeAttribute:
    groupMemberAttribute: member
    sortControlSupported: false
    useSsl: true
    usePosixGroups: false
    allowAnonymousLogin: false
    acceptUntrustedCertificates: true
    authorizationCheckEnabled: false
  administrator:
      administratorGroupName: CamundaAdmins
#      administratorGroupName: Administrators
#      administratorUserName: CamundaAdmin
#      administratorUserName: Administrator


#security:
#    ldap:
#      initialContextFactory: com.sun.jndi.ldap.LdapCtxFactory
#      securityAuthentication: simple
#      serverUrl: ldap://MOLLY.AQUARIUM.tank:389
#      managerDn: CN=CamundaAdmin,CN=Users,DC=AQUARIUM,DC=tank
#      managerPassword: CamundaAdmin
#      baseDn: DC=AQUARIUM,DC=tank
#      userDnPattern:
#      userSearchBase: CN=Users
#      userSearchFilter: (objectclass=person)
#      groupSearchBase:
#      groupSearchFilter: (objectclass=group)
#      userIdAttribute: cn
#      userFirstnameAttribute: givenName
#      userLastnameAttribute: sn
#      userEmailAttribute: mail
#      userPasswordAttribute: userpassword
#      groupIdAttribute: cn
#      groupNameAttribute: name
#      groupTypeAttribute:
#      groupMemberAttribute: member
#      sortControlSupported: false
#      useSsl: false
#      usePosixGroups: false
#      allowAnonymousLogin: false
#      acceptUntrustedCertificates: true
#      authorizationCheckEnabled: false
#    administrator:
#      administratorGroupName: CamundaAdmins
##      administratorGroupName: Administrators
##      administratorUserName: CamundaAdmin
##      administratorUserName: Administrator

server:
  port : 8080

# H2 datasource
spring:
  h2.console.enabled: true
  datasource:
    #    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:camunda-db
    username: sa
    password: sa

## MS SQL Server datasource
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1417;databaseName=camunda_cs
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: Camunda1

## Oracle datasource
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: camunda
#    password: Camunda1

# Logging Settings
logging:
  file:
    path: ./logs           # specify a path to write to file, otherwise it defaults to the console.
  level:
    # Camunda Loggers
    org.camunda: INFO     # WARNING!! THIS NAMESPACE WILL OUTPUT ALL CAMUNDA LOGS AT THE SPECIFIED LEVEL.
    org.example.spring.boot.ldap.ad1: DEBUG
#    org.camunda.bpm.engine.cmd: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity: DEBUG
#    org.camunda.bpm.engine.impl.batch.BatchEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.IncidentEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.JobEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.VariableInstanceEntity: DEBUG
#    org.camunda.bpm.engine.jobexecutor: DEBUG
#    org.camunda.bpm.engine.persistence: DEBUG
#    org.camunda.bpm.engine.tx: DEBUG
#    # Common Camunda Dependencies
#    org.apache.ibatis: INFO
#    # Add Catalina logging
#    org.apache.catalina: INFO
#    # Add Tomcat logging
#    org.apache.tomcat: INFO
